---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secretless-config
  namespace: {{ DEMOAPPS_NAMESPACE }}
data:
  secretless.yml: |
    version: "2"
    services:
      mssql-db:
        protocol: mssql
        listenOn: tcp://0.0.0.0:1433 # can be a socket as well (same name for both)
        credentials:
          host: 
            from: conjur
            get: dev/okd3-cluster1/secretless-db/host
          port: 
            from: conjur
            get: dev/okd3-cluster1/secretless-db/port
          username:
            from: conjur
            get: dev/okd3-cluster1/secretless-db/username
          password:
            from: conjur
            get: dev/okd3-cluster1/secretless-db/password
          sslmode: require
        config:  # this section usually blank
          optionalStuff: foo

      postgres-db:
        protocol: pg
        listenOn: tcp://0.0.0.0:5432 # can be a socket as well (same name for both)
        credentials:
          host: 
            from: conjur
            get: dev/okd3-cluster1/secretless-db/host
          port: 
            from: conjur
            get: dev/okd3-cluster1/secretless-db/port
          username:
            from: conjur
            get: dev/okd3-cluster1/secretless-db/username
          password:
            from: conjur
            get: dev/okd3-cluster1/secretless-db/password
          sslmode: require
        config:  # this section usually blank
          optionalStuff: foo
  
      mysql-db:
        protocol: mysql
        listenOn: tcp://0.0.0.0:3306 # can be a socket as well (same name for both)
        credentials:
          host: 
            from: conjur
            get: dev/okd3-cluster1/secretless-db/host
          port: 
            from: conjur
            get: dev/okd3-cluster1/secretless-db/port
          username:
            from: conjur
            get: dev/okd3-cluster1/secretless-db/username
          password:
            from: conjur
            get: dev/okd3-cluster1/secretless-db/password
          sslmode: require
        config:  # this section usually blank
          optionalStuff: foo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretless
  namespace: {{ DEMOAPPS_NAMESPACE }}
  labels:
    app: secretless
spec:
  replicas: 1
  selector:
    matchLabels:
      role: demo
      app: secretless
  template:
    metadata:
      labels:
        role: demo
        app: secretless
    spec:
      serviceAccountName: {{ SECRETLESS_SERVICEACCOUNT }}
      shareProcessNamespace: true
      containers:
      - name: secretless-broker
        image: {{ SECRETLESS_BROKER_IMAGE }}
        args: ["-f", "/etc/secretless/secretless.yml"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: {{ CONJUR_APPLIANCE_URL }}
          - name: CONJUR_AUTHN_URL
            value: {{ CONJUR_AUTHN_URL }}
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}
          - name: CONJUR_AUTHN_LOGIN
            value: {{ SECRETLESS_CONJUR_AUTHN_LOGIN }}
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: dap-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /etc/secretless
            name: config
            readOnly: true
          - mountPath: /run/conjur
            name: conjur-access-token
      - name: demoapp
        image: {{ SECRETLESS_APP_IMAGE }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        env:
          - name: DB_URL
            value: {{ SECRETLESS_DB_URL }}
          - name: DB_PLATFORM
            value: {{ DEMOAPPS_DB }}
      #imagePullSecrets:
        #- name: dockerpullsecret-secretless-account
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: config
          configMap:
            name: secretless-config
            defaultMode: 420