---
- &authenticated-resources
  - !host
    id: k8s-provider-account
    annotations:
      authn-k8s/namespace: demoapps-xqcb-syst
      authn-k8s/service-account: k8s-provider-account
      kubernetes/authentication-container-name: authenticator
      kubernetes: true

- !grant
  role: !layer
  members: *authenticated-resources

- &demoapps-k8sprovider-variables
  - !variable url
  - !variable username
  - !variable password

- !permit
  role: !layer
  privileges: [ "read", "execute" ]
  resources: *demoapps-k8sprovider-variables