---
- &authenticated-resources
  - !host
    id: secretless-account
    annotations:
      authn-k8s/namespace: demoapps
      authn-k8s/service-account: secretless-account
      kubernetes/authentication-container-name: secretless-broker
      kubernetes: true

- !grant
  role: !layer
  members: *authenticated-resources

- &demoapps-secretless-variables
  - !variable host
  - !variable port
  - !variable username
  - !variable password

- !permit
  role: !layer
  privileges: [ "read", "execute" ]
  resources: *demoapps-secretless-variables