apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dapfollowers.dap.cyberark.com
spec:
  group: dap.cyberark.com
  names:
    kind: DAPFollower
    listKind: DAPFollowerList
    plural: dapfollowers
    singular: dapfollower
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DAPFollower is the Schema for the dapfollowers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DAPFollowerSpec defines the desired state of DAPFollower
            properties:
              authenticatorId:
                type: string
              clusterRoleBindingName:
                type: string
              clusterRoleName:
                type: string
              configMapName:
                type: string
              conjurAccount:
                type: string
              conjurAuthnLogin:
                type: string
              dapMasterHostname:
                type: string
              deploymentName:
                type: string
              followerReplicas:
                format: int32
                type: integer
              images:
                description: DAPFollowerImages defines the image names for the Follower
                  containers
                properties:
                  conjur:
                    type: string
                  info:
                    type: string
                  nginx:
                    type: string
                  postgres:
                    type: string
                  seedFetcher:
                    type: string
                  syslogNg:
                    type: string
                type: object
              serviceAccountName:
                type: string
              serviceName:
                type: string
            required:
            - images
            type: object
          status:
            description: DAPFollowerStatus defines the observed state of DAPFollower
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
