---
#This policy defines permissions for testapp project resources in kubernetes cluster
- !policy
  id: secretless-db
  owner: !group /k8s-cluster1-admins
  body:
    - !layer
      annotations:
        kubernetes: true

- !policy
  id: goapp
  owner: !group /k8s-cluster1-admins
  body:
    - !layer
      annotations:
        kubernetes: true

- !policy
  id: goapp-epv
  owner: !group /k8s-cluster1-admins
  body:
    - !layer
      annotations:
        kubernetes: true

- !policy
  id: java-init-db
  owner: !group /k8s-cluster1-admins
  body:
    - !layer
      annotations:
        kubernetes: true

- !policy
  id: java-sidecar-db
  owner: !group /k8s-cluster1-admins
  body:
    - !layer
      annotations:
        kubernetes: true
    
- !policy
  id: k8s-provider-db
  owner: !group /k8s-cluster1-admins
  body:
    - !layer
      annotations:
        kubernetes: true