---
## Permissions
- !grant
  role: !layer authn-k8s/okd3-cluster1/secretless-db
  members:
  - !layer /dev/okd3-cluster1/secretless-db

- !grant
  role: !layer authn-k8s/okd3-cluster1/goapp
  members:
  - !layer /dev/okd3-cluster1/goapp

- !grant
  role: !layer authn-k8s/okd3-cluster1/goapp-epv
  members:
  - !layer /dev/okd3-cluster1/goapp-epv

- !grant
  role: !layer authn-k8s/okd3-cluster1/java-init-db
  members:
  - !layer /dev/okd3-cluster1/java-init-db

- !grant
  role: !layer authn-k8s/okd3-cluster1/java-sidecar-db
  members:
  - !layer /dev/okd3-cluster1/java-sidecar-db

- !grant
  role: !layer authn-k8s/okd3-cluster1/k8s-provider-db
  members:
  - !layer /dev/okd3-cluster1/k8s-provider-db