---
- &authenticated-resources
  - !host
    id: java-init-app-account
    annotations:
      authn-k8s/namespace: demoapps-xqcb-syst
      authn-k8s/service-account: java-init-app-account
      authn-k8s/authentication-container-name: authenticator
      openshift: true

- !grant
  role: !layer
  members: *authenticated-resources

- &demoapps-java-variables
  - !variable url
  - !variable username
  - !variable password

- !permit
  role: !layer
  privileges: [ "read", "execute" ]
  resources: *demoapps-java-variables