kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-dap-operator
subjects:
- kind: ServiceAccount
  name: openshift-dap-operator
  namespace: cyberark-xqcb-syst
roleRef:
  kind: ClusterRole
  name: openshift-dap-operator
  apiGroup: rbac.authorization.k8s.io
